CREATE TABLE IF NOT EXISTS TBL_USER (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME TEXT NOT NULL CHECK (LENGTH(FIRST_NAME) <= 20),
    LAST_NAME TEXT NOT NULL CHECK (LENGTH(LAST_NAME) <= 50),
    EMAIL TEXT NOT NULL UNIQUE CHECK (LENGTH(EMAIL) <= 30),
    PASSWORD TEXT NOT NULL
);
